name: todoapp CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for server
        run: |
          cd server
          npm install
        continue-on-error: true

      - name: Install dependencies for client
        run: |
          cd client
          npm install
        continue-on-error: true

      - name: Build client
        run: |
          cd client
          npm run build

        continue-on-error: true
        
      - name: PM2 Service
      run: |
        pm2 stop 0
        pm2 start 0
        pm2 save
        sudo service nginx restart

      - name: Test client
        run: |
          cd client
          npm test
        continue-on-error: true

      - name: Test server
        run: |
          cd server
          npm test
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DB: test_db
        continue-on-error: true

      - name: Lint client
        run: |
          cd client
          npm run lint
        continue-on-error: true

      - name: Lint server
        run: |
          cd server
          npm run lint
        continue-on-error: true

